declare module 'lucide-react' {
  import * as React from 'react';
  export type LucideProps = React.SVGProps<SVGSVGElement> & {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
  };
  export type LucideIcon = React.FC<LucideProps>;

  export const LayoutDashboard: LucideIcon;
  export const PlusCircle: LucideIcon;
  export const Plus: LucideIcon;
  export const FileSpreadsheet: LucideIcon;
  export const FileText: LucideIcon;
  export const Bot: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Settings: LucideIcon;
  export const Sparkles: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Bell: LucideIcon;
  export const User: LucideIcon;
  export const Check: LucideIcon;
  export const Shield: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const Flame: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Clock: LucideIcon;
  export const Trash2: LucideIcon;
  export const Droplet: LucideIcon;
  export const Zap: LucideIcon;
  export const Wind: LucideIcon;
  export const Trees: LucideIcon;
  export const Layers: LucideIcon;
  export const Award: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const MapPin: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const Image: LucideIcon;
  export const X: LucideIcon;
  export const Loader2: LucideIcon;
  export const PieChart: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Calendar: LucideIcon;
  export const Wrench: LucideIcon;
  export const Save: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const Square: LucideIcon;
  export const Search: LucideIcon;
  export const Filter: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Send: LucideIcon;
  export const Database: LucideIcon;
  export const Sun: LucideIcon;
  export const Moon: LucideIcon;
  export const Info: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const FileCheck2: LucideIcon;
  export const Percent: LucideIcon;
  export const BellRing: LucideIcon;

  // Eco-Bounty Icons
  export const Trophy: LucideIcon;
  export const Coins: LucideIcon;
  export const Mic: LucideIcon;
  export const MicOff: LucideIcon;
  export const Volume2: LucideIcon;
  export const Gift: LucideIcon;
  export const Medal: LucideIcon;
  export const Target: LucideIcon;
  export const Users: LucideIcon;
  export const CheckCheck: LucideIcon;
  export const Star: LucideIcon;
  export const Radio: LucideIcon;
  export const Building2: LucideIcon;
  export const Sparkle: LucideIcon;
  export const Camera: LucideIcon;
  
  const allIcons: Record<string, LucideIcon>;
  export default allIcons;
}
