import { EnvironmentalIssue, EcoAuditor, EcoBountyStats } from './types';
import { estimateResourceImpact } from './impact-estimator';
import { generateRootCauseAnalysis } from './root-cause';

const RAW_ISSUES: EnvironmentalIssue[] = [
  // --- IT BLOCK RECURRING ENERGY WASTE (5 Incidents) ---
  {
    id: 'EB-1042',
    title: 'Lights and fans left ON in empty classroom',
    description: 'Lights and fans are left running in IT Block Room 302 after class dismissed.',
    category: 'energy',
    location: 'IT Block',
    severity: 'high',
    status: 'in_progress',
    image_url: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Continuous illumination and ventilation operating in vacant classroom with no scheduled session.',
    ai_observations: [
      'Multiple ceiling fluorescent lights are visibly active',
      'Ceiling fans operating at maximum speed',
      'No people are clearly visible in the provided image',
      'Blackboard indicates previous lecture ended at 16:30'
    ],
    ai_impact: 'Superfluous electrical consumption contributing to peak grid demand and fixture wear.',
    ai_recommendations: [
      'Disengage manual master switches near Room 302 door',
      'Verify corridor breaker panel'
    ],
    ai_preventive_actions: [
      'Install PIR motion occupancy sensors',
      'Enforce classroom shutdown checks before lock-up'
    ],
    ai_confidence: 0.94,
    ai_uncertainty: [
      'AI can identify visible lights and fans, but it cannot confirm actual electricity consumption or whether the room is officially unoccupied.'
    ],
    maintenance_required: true,
    reported_by: 'Elakkiyan (Student Auditor)',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 mins ago
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
    voice_transcript: 'Lights and fans are left on in IT Block Room 302.',
  },
  {
    id: 'GM-2026-IT-1',
    title: 'Split AC left running at 18°C in empty seminar room',
    description: 'Two 2-ton split air conditioning units left running continuously in vacant IT Block Seminar Hall 2 over the weekend.',
    category: 'energy',
    location: 'IT Block',
    severity: 'high',
    status: 'open',
    image_url: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Heavy HVAC compressor cooling active in unreserved hall during non-operational weekend hours.',
    ai_observations: [
      'Air conditioning display showing 18°C setpoint in vacant hall',
      'Thermostat compressor running at high load',
      'Doors and windows closed with no scheduled workshop'
    ],
    ai_impact: 'Avoidable continuous load of ~3.6 kW wasting upwards of 70 kWh over 48 hours.',
    ai_recommendations: ['Shut off AC power via isolator switch near entrance', 'Notify facilities keyholder'],
    ai_preventive_actions: ['Fit smart HVAC auto-off timers coupled to central room reservation calendar'],
    ai_confidence: 0.95,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Campus Security Patrol',
    created_at: new Date(Date.now() - 52 * 3600 * 1000).toISOString(), // 52 hours ago (unresolved!)
    updated_at: new Date(Date.now() - 52 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: false,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
  },
  {
    id: 'GM-2026-IT-2',
    title: 'Ceiling fluorescent tubes left on overnight in Room 204',
    description: 'Entire bank of 12 fluorescent lights left illuminated all night in IT Block Room 204.',
    category: 'energy',
    location: 'IT Block',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Overnight illumination left unmanaged following evening lab session.',
    ai_observations: ['All 12 tube lights active', 'No occupants present'],
    ai_impact: 'Idle energy burn of ~0.6 kW over 9 hours.',
    ai_recommendations: ['Switch off main classroom breaker'],
    ai_preventive_actions: ['Install 30-minute auto-timeout light switches'],
    ai_confidence: 0.93,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Priya K. (Student Auditor)',
    resolution_notes: 'Turned off by night warden at 06:00. Room instructor notified.',
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(), // 7 days ago
    updated_at: new Date(Date.now() - 7 * 24 * 3600 * 1000 + 4 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 7 * 24 * 3600 * 1000 + 4 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
  },
  {
    id: 'GM-2026-IT-3',
    title: 'High-performance computing lab AC running unoccupied',
    description: 'Auxiliary cooling fans and room AC running full speed in IT Block Lab 3 with zero system benchmarks running.',
    category: 'energy',
    location: 'IT Block',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Air conditioning set to low temperature in vacant server lab.',
    ai_observations: ['Lab empty', 'AC running at maximum cooling'],
    ai_impact: 'Consumes approximately 2.8 kWh per unoccupied hour.',
    ai_recommendations: ['Set thermostat to eco mode (24°C)'],
    ai_preventive_actions: ['Automate temperature setback based on server thermal sensors'],
    ai_confidence: 0.91,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Kavin R. (Auditor)',
    resolution_notes: 'Temperature normalized to 24°C by lab technician.',
    created_at: new Date(Date.now() - 16 * 24 * 3600 * 1000).toISOString(), // 16 days ago
    updated_at: new Date(Date.now() - 16 * 24 * 3600 * 1000 + 2 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 16 * 24 * 3600 * 1000 + 2 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
  },
  {
    id: 'GM-2026-IT-4',
    title: 'Corridor lighting banks illuminated during midday sun',
    description: 'All 8 corridor light banks on IT Block Level 2 turned on despite abundant natural sunlight from atrium skylight.',
    category: 'energy',
    location: 'IT Block',
    severity: 'low',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Daylight harvesting failure with manual lights kept active in daylight.',
    ai_observations: ['Natural ambient light exceeds 500 lux', 'Tubes burning unnecessarily'],
    ai_impact: 'Avoidable daytime electrical waste.',
    ai_recommendations: ['Toggle off corridor bank switch'],
    ai_preventive_actions: ['Install lux-level daylight sensor relays'],
    ai_confidence: 0.92,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Arun M. (Auditor)',
    resolution_notes: 'Switches turned off. Facilities scheduled sensor upgrade.',
    created_at: new Date(Date.now() - 38 * 24 * 3600 * 1000).toISOString(), // 38 days ago
    updated_at: new Date(Date.now() - 38 * 24 * 3600 * 1000 + 1 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 38 * 24 * 3600 * 1000 + 1 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 20,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
  },

  // --- BOYS HOSTEL BLOCK B RECURRING WATER LEAKS (6 Incidents: 4 in last 30 days) ---
  {
    id: 'GM-2026-002',
    title: 'Severe pipeline water leakage',
    description: 'Continuous water leakage from main ground floor washroom pipe in Boys Hostel Block B.',
    category: 'water',
    location: 'Boys Hostel Block B',
    severity: 'high',
    status: 'open',
    image_url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Pressurized water leakage from hostel plumbing line resulting in water pooling and structural dampness.',
    ai_observations: [
      'Steady stream of clean water escaping from pipe joint',
      'Standing water pooling along the corridor edge (approx 15 sqm)',
      'Slip hazard risk for residents'
    ],
    ai_impact: 'Estimated freshwater loss of 25–40 liters per hour. Prolonged pooling risks concrete erosion and water damage.',
    ai_recommendations: [
      'Isolate main valve B-2 immediately',
      'Deploy warning wet floor signage',
      'Replace worn seal gasket'
    ],
    ai_preventive_actions: [
      'Conduct monthly plumbing pressure checks across all hostel wings',
      'Replace aging PVC connectors with reinforced copper/brass joints'
    ],
    ai_confidence: 0.92,
    ai_uncertainty: ['Exact crack location behind drywall requires physical access'],
    maintenance_required: true,
    reported_by: 'Karthik Raja (Maintenance Staff)',
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(), // 12 mins ago (in last 30 days #1)
    updated_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: false,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  },
  {
    id: 'GM-2026-BH-1',
    title: 'Washroom pipe joint dripping and pooling',
    description: 'Persistent water dripping from copper elbow connector in Boys Hostel Block B second floor washroom.',
    category: 'water',
    location: 'Boys Hostel Block B',
    severity: 'high',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Repeated joint seal weepage causing standing puddle near cubicles.',
    ai_observations: ['Continuous drip from elbow joint', 'Tile floor slick with water film'],
    ai_impact: 'Loss of ~20 liters per hour clean potable water.',
    ai_recommendations: ['Tighten flange coupling', 'Replace Teflon seal ring'],
    ai_preventive_actions: ['Execute preventative plumbing inspection across all Block B risers'],
    ai_confidence: 0.93,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Arun M. (Hostel Resident Auditor)',
    resolution_notes: 'Plumber replaced rubber O-ring seal and tightened coupling.',
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(), // 3 days ago (in last 30 days #2)
    updated_at: new Date(Date.now() - 3 * 24 * 3600 * 1000 + 6 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 3 * 24 * 3600 * 1000 + 6 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  },
  {
    id: 'GM-2026-BH-2',
    title: 'Overhead header pipe flange seepage',
    description: 'Water spraying in fine mist from overhead main header pipe in Boys Hostel Block B utility duct.',
    category: 'water',
    location: 'Boys Hostel Block B',
    severity: 'high',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Pressure surge spray from aging gasket in utility duct.',
    ai_observations: ['High-pressure mist escaping flange joint', 'Moisture staining ceiling plaster'],
    ai_impact: 'Loss of ~50 liters/hour; risks ceiling dampness.',
    ai_recommendations: ['Depressurize line and replace fiber gasket'],
    ai_preventive_actions: ['Fit pressure relief valve on main hostel riser'],
    ai_confidence: 0.94,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Deepak V. (Auditor)',
    resolution_notes: 'New industrial rubber gasket installed. Line pressure re-balanced.',
    created_at: new Date(Date.now() - 11 * 24 * 3600 * 1000).toISOString(), // 11 days ago (in last 30 days #3)
    updated_at: new Date(Date.now() - 11 * 24 * 3600 * 1000 + 4 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 11 * 24 * 3600 * 1000 + 4 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  },
  {
    id: 'GM-2026-BH-3',
    title: 'Shower head valve failure and steady leak',
    description: 'Shower shutoff valve failed in Boys Hostel Block B 3rd floor washroom, discharging water continuously.',
    category: 'water',
    location: 'Boys Hostel Block B',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Internal brass valve cartridge failed to seal shut.',
    ai_observations: ['Continuous stream into shower tray', 'Valve handle spinning freely'],
    ai_impact: 'Wasting approximately 120 liters of water daily.',
    ai_recommendations: ['Replace internal quarter-turn ceramic cartridge'],
    ai_preventive_actions: ['Standardize on commercial grade vandal-proof ceramic valves'],
    ai_confidence: 0.92,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Sneha B. (Auditor)',
    resolution_notes: 'Valve core replaced by hostel maintenance plumber.',
    created_at: new Date(Date.now() - 22 * 24 * 3600 * 1000).toISOString(), // 22 days ago (in last 30 days #4)
    updated_at: new Date(Date.now() - 22 * 24 * 3600 * 1000 + 8 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 22 * 24 * 3600 * 1000 + 8 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  },
  {
    id: 'GM-2026-BH-4',
    title: 'Corridor plumbing line seepage and wall peeling',
    description: 'Under-plaster pipe leakage causing extensive paint blistering and dripping in Boys Hostel Block B ground floor.',
    category: 'water',
    location: 'Boys Hostel Block B',
    severity: 'high',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Sub-surface concealed pipe fracture causing wall efflorescence and floor dampness.',
    ai_observations: ['Wall plaster damp and bubbling', 'Persistent water trail across hallway'],
    ai_impact: 'Long-term masonry decay and loss of treated water.',
    ai_recommendations: ['Patch and seal leaking section', 'Inspect adjacent conduit joints'],
    ai_preventive_actions: ['Schedule comprehensive non-destructive ultrasonic leak audit for Block B'],
    ai_confidence: 0.90,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Hostel Warden',
    resolution_notes: 'Wall opened, pinhole copper leak brazed, and plastered.',
    created_at: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(), // 45 days ago (#5)
    updated_at: new Date(Date.now() - 44 * 24 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 44 * 24 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  },
  {
    id: 'GM-2026-BH-5',
    title: 'Ground floor main riser union weeping',
    description: 'Slow continuous drip from threaded union on vertical supply riser in Boys Hostel Block B entrance closet.',
    category: 'water',
    location: 'Boys Hostel Block B',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Threaded pipe union weeping water beneath insulation wrap.',
    ai_observations: ['Insulation foam saturated with moisture', 'Slow drip (approx 1 drop every 2 seconds)'],
    ai_impact: 'Gradual loss of 15 liters daily, corrosive damage to metallic conduit.',
    ai_recommendations: ['Disassemble union, apply thread sealant paste, and re-torque'],
    ai_preventive_actions: ['Replace aged galvanized iron fittings with brass unions'],
    ai_confidence: 0.89,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Karthik Raja (Maintenance Staff)',
    resolution_notes: 'Union re-sealed with PTFE tape and pipe compound.',
    created_at: new Date(Date.now() - 58 * 24 * 3600 * 1000).toISOString(), // 58 days ago (#6)
    updated_at: new Date(Date.now() - 57 * 24 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 57 * 24 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  },

  // --- BLOCK 3 RECURRING OVERFLOWING BINS (4 Incidents) ---
  {
    id: 'GM-2026-001',
    title: 'Overflowing waste bin near entrance',
    description: 'There is a lot of plastic waste near Block 3 and the dustbin is overflowing onto the walkway.',
    category: 'waste',
    location: 'Block 3',
    severity: 'high',
    status: 'in_progress',
    image_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Overflowing waste collection point with visible plastic accumulation spilling onto pedestrian walkway.',
    ai_observations: [
      'Waste is accumulated around the collection point',
      'High volume of single-use plastic cups and food wrappers visible',
      'Bin is well above 100% capacity',
      'Pedestrian walkway partially obstructed'
    ],
    ai_impact: 'Accumulated waste creates sanitary hazards, attracts campus pests, and risks plastic runoff into storm drains during rain.',
    ai_recommendations: [
      'Dispatch sanitation crew immediately for clearing',
      'Provide secondary recycling bin',
      'Audit lunch-hour disposal capacity'
    ],
    ai_preventive_actions: [
      'Increase collection frequency during peak hours (12 PM - 3 PM)',
      'Install high-visibility waste segregation signage',
      'Upgrade to dual 120L sorting receptacles'
    ],
    ai_confidence: 0.94,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Aarav Sharma (Student Auditor)',
    resolution_notes: 'Sanitation team notified. Heavy duty bins requested from facilities.',
    created_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(), // 28 mins ago
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Campus Sanitation',
  },
  {
    id: 'GM-2026-B3-1',
    title: 'Plastic food containers overflowing at Block 3 east staircase',
    description: 'Post-lunch takeaway plastic boxes piled 2 feet above bin rim at Block 3 east staircase landing.',
    category: 'waste',
    location: 'Block 3',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Lunch hour container accumulation exceeding bin volume.',
    ai_observations: ['Disposable lunch containers spilled on floor', 'Recycling bin filled with mixed garbage'],
    ai_impact: 'Sanitary hazard and plastic litter blowing into adjoining lawns.',
    ai_recommendations: ['Clear bin immediately', 'Add dedicated food container disposal hamper'],
    ai_preventive_actions: ['Introduce compostable lunch packaging incentives with canteen vendor'],
    ai_confidence: 0.91,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Priya K. (Auditor)',
    resolution_notes: 'Cleared by sanitation staff and additional bin placed.',
    created_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(), // 4 days ago
    updated_at: new Date(Date.now() - 4 * 24 * 3600 * 1000 + 3 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 4 * 24 * 3600 * 1000 + 3 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Campus Sanitation',
  },
  {
    id: 'GM-2026-B3-2',
    title: 'Juice cups and beverage packaging littering Block 3 courtyard',
    description: 'Discarded paper and plastic beverage cups overflowing small perimeter bins around Block 3 courtyard.',
    category: 'waste',
    location: 'Block 3',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Courtyard perimeter receptacles overwhelmed by beverage cups.',
    ai_observations: ['Over 30 disposable cups scattered around planter box', 'Bin at 120% capacity'],
    ai_impact: 'Unsorted plastic degradation and ground littering.',
    ai_recommendations: ['Empty courtyard bins twice daily'],
    ai_preventive_actions: ['Install cup-stacking recycling tubes next to beverage kiosks'],
    ai_confidence: 0.90,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Elakkiyan (Auditor)',
    resolution_notes: 'Waste swept and new collection bags installed.',
    created_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(), // 14 days ago
    updated_at: new Date(Date.now() - 14 * 24 * 3600 * 1000 + 2 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 14 * 24 * 3600 * 1000 + 2 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Campus Sanitation',
  },
  {
    id: 'GM-2026-B3-3',
    title: 'Cardboard and takeaway boxes overflowing collection bin',
    description: 'Packaging boxes and uncompressed cardboard dumped haphazardly outside Block 3 rear loading dock.',
    category: 'waste',
    location: 'Block 3',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Unflattened cardboard boxes clogging general waste dumpster.',
    ai_observations: ['Dumpster lid jammed open by oversized boxes', 'Cardboard soggy from rain'],
    ai_impact: 'Reduced dumpster capacity forcing other waste onto pavement.',
    ai_recommendations: ['Flatten cardboard and bundle for paper recycler'],
    ai_preventive_actions: ['Provide dedicated cardboard baling cage at loading zone'],
    ai_confidence: 0.92,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Facilities General',
    resolution_notes: 'Cardboard flattened and loaded into paper recycling truck.',
    created_at: new Date(Date.now() - 27 * 24 * 3600 * 1000).toISOString(), // 27 days ago
    updated_at: new Date(Date.now() - 27 * 24 * 3600 * 1000 + 5 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 27 * 24 * 3600 * 1000 + 5 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Campus Sanitation',
  },

  // --- GARDEN RECURRING BROKEN SPRINKLERS (3 Incidents) ---
  {
    id: 'GM-2026-005',
    title: 'Desiccated plants and failing irrigation',
    description: 'Ornamental shrubbery and flowering beds dried up near Central Garden due to broken sprinkler line.',
    category: 'green_cover',
    location: 'Garden',
    severity: 'medium',
    status: 'in_progress',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Severe soil dryness and foliage wilting in central landscaped zone due to automated irrigation outage.',
    ai_observations: [
      'Vegetation exhibiting browning leaves and dry brittle soil crust',
      'Drip irrigation line severed near zone 3 border',
      'Native flora under acute moisture stress'
    ],
    ai_impact: 'Loss of native pollinator habitat, reduced campus heat island mitigation, and aesthetic degradation.',
    ai_recommendations: [
      'Manual deep watering session using recycled greywater bowser',
      'Splice and repair broken poly-pipe section'
    ],
    ai_preventive_actions: [
      'Install soil moisture probe telemetry for early drought alerts',
      'Apply organic woodchip mulch to retain ground moisture'
    ],
    ai_confidence: 0.91,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Campus Landscaping Team',
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(), // 4 hrs ago
    updated_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Horticulture & Grounds',
  },
  {
    id: 'GM-2026-GD-1',
    title: 'Broken sprinkler head spraying onto pedestrian pathway',
    description: 'Pop-up rotary sprinkler head snapped in Central Garden, geysering pressurized water onto pedestrian walkway instead of grass.',
    category: 'green_cover',
    location: 'Garden',
    severity: 'high',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Mechanical shear of irrigation head causing water plume over pathway.',
    ai_observations: ['High-pressure fountain spraying 3 meters high', 'Walkway flooded with 2 inches of runoff'],
    ai_impact: 'Excessive water waste (~400 L/hr) and pathway pedestrian hazard.',
    ai_recommendations: ['Shut solenoid valve zone 4', 'Replace cracked sprinkler riser'],
    ai_preventive_actions: ['Fit impact-resistant stainless steel riser guards along lawn edges'],
    ai_confidence: 0.94,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Suresh Menon (Auditor)',
    resolution_notes: 'Zone 4 isolated and new commercial pop-up head fitted.',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(), // 5 days ago
    updated_at: new Date(Date.now() - 5 * 24 * 3600 * 1000 + 3 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 5 * 24 * 3600 * 1000 + 3 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Horticulture & Grounds',
  },
  {
    id: 'GM-2026-GD-2',
    title: 'Severed drip line weeping in shrubbery zone',
    description: 'Ground maintenance mower clipped flexible drip hose in Central Garden, creating continuous muddy puddle.',
    category: 'green_cover',
    location: 'Garden',
    severity: 'medium',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Severed subsurface flexible drip line leaking in landscaped bed.',
    ai_observations: ['Water pooling in mulch bed', 'Punctured 16mm LDPE pipe visible'],
    ai_impact: 'Localized waterlogging and root rot risks for ornamentals.',
    ai_recommendations: ['Splice line with barbed coupler connector'],
    ai_preventive_actions: ['Bury drip lines minimum 3 inches below mulch grade'],
    ai_confidence: 0.90,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Groundskeeping Staff',
    resolution_notes: 'Line spliced with dual barbed lock fittings.',
    created_at: new Date(Date.now() - 19 * 24 * 3600 * 1000).toISOString(), // 19 days ago
    updated_at: new Date(Date.now() - 19 * 24 * 3600 * 1000 + 4 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 19 * 24 * 3600 * 1000 + 4 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Horticulture & Grounds',
  },

  // --- LOCATION WITH INSUFFICIENT DATA (1 Incident) ---
  {
    id: 'GM-2026-LIB-1',
    title: 'Defective reading lamp flickering in Library 1st Floor',
    description: 'Single desk reading lamp ballast failure on Library east study desk.',
    category: 'energy',
    location: 'Library',
    severity: 'low',
    status: 'open',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Individual lamp fixture ballast buzzing and strobing.',
    ai_observations: ['Single desk light flickering', 'No other lights affected'],
    ai_impact: 'Minor aesthetic nuisance and modest energy draw.',
    ai_recommendations: ['Replace lamp bulb with 9W LED'],
    ai_preventive_actions: ['Routine library lighting inspection'],
    ai_confidence: 0.96,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Sneha B. (Student)',
    created_at: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(), // 12 days ago
    updated_at: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 20,
    eco_bounty_rewarded: false,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
  },

  // --- OTHER STANDARD CAMPUS INCIDENTS ---
  {
    id: 'GM-2026-003',
    title: 'Lights and AC left on overnight',
    description: 'All 8 fluorescent lights and 2 air conditioning units left running in empty Lab 4.',
    category: 'energy',
    location: 'Laboratory',
    severity: 'low',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Unoccupied computer lab running HVAC and illumination outside scheduled lab operational hours.',
    ai_observations: [
      'Lab completely vacant of students and faculty',
      'Main ambient lighting banks active',
      'Thermostat set to 18°C while ambient temp is comfortable'
    ],
    ai_impact: 'Unnecessary electrical consumption of ~6.4 kWh per night; accelerates equipment wear and carbon footprint.',
    ai_recommendations: ['Turn off switches on console 4', 'Reset AC timer circuit'],
    ai_preventive_actions: [
      'Install PIR motion occupancy sensors',
      'Enforce end-of-day lab shutdown checklist for lab instructors'
    ],
    ai_confidence: 0.96,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Campus Security Patrol',
    resolution_notes: 'Lights and AC powered off by night warden at 23:45. Instructor reminded.',
    created_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 20,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
  },
  {
    id: 'GM-2026-004',
    title: 'Single-use plastic food containers litter',
    description: 'Extensive plastic bottles and food takeaway packaging scattered across canteen seating quad.',
    category: 'plastic',
    location: 'Canteen',
    severity: 'medium',
    status: 'open',
    image_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Accumulation of disposable plastic containers and beverage bottles in open-air dining area.',
    ai_observations: [
      'Multiple PET bottles discarded on tables and stone benches',
      'Disposable plastic cutlery and sauce sachets in planter boxes'
    ],
    ai_impact: 'Visual blight, plastic ingestion risks for campus fauna, microplastic degradation under UV sunlight.',
    ai_recommendations: ['Place 3 additional segregated waste bins adjacent to seating pods', 'Organize immediate canteen sweep'],
    ai_preventive_actions: ['Transition campus canteen vendors to biodegradable paper/bagasse containers'],
    ai_confidence: 0.88,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Priya N. (Student Auditor)',
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: false,
    ai_verified: true,
    assigned_department: 'Campus Sanitation',
  },
  {
    id: 'GM-2026-006',
    title: 'Continuous running tap in restroom',
    description: 'Faucet valve failed open in second-floor washroom of Block 2. Water running unchecked.',
    category: 'water',
    location: 'Block 2',
    severity: 'high',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Stuck push-cartridge faucet discharging full mains pressure into washbasin overflow.',
    ai_observations: ['Continuous stream from tap into drainage basin', 'Internal valve spring appears jammed'],
    ai_impact: 'Wasting approximately 600 liters per hour of treated potable water.',
    ai_recommendations: ['Close angle stopcock beneath the sink', 'Replace ceramic cartridge assembly'],
    ai_preventive_actions: ['Standardize on vandal-resistant aerators with 1.5 LPM flow restrictors across all academic buildings'],
    ai_confidence: 0.95,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Deepak V. (Student Auditor)',
    resolution_notes: 'Angle stop valve turned off and cartridge replaced with brass auto-timed push valve.',
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  },
  {
    id: 'GM-2026-008',
    title: 'High-intensity spotlights active during daytime',
    description: 'Four 400W halogen architectural spotlights left illuminated at midday in Seminar Hall atrium.',
    category: 'energy',
    location: 'Seminar Hall',
    severity: 'low',
    status: 'open',
    image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Daylight harvesting failure where high-wattage lighting operates despite adequate natural skylight.',
    ai_observations: ['Four commercial halogen fixtures powered on unnecessarily', 'Manual switch locked ON'],
    ai_impact: 'Superfluous 1.6 kW continuous load plus additional cooling load on auditorium chiller plant.',
    ai_recommendations: ['Toggle main breaker panel 3 to auto-lux sensing mode', 'Notify event manager'],
    ai_preventive_actions: ['Install photocell daylight sensors to automatically suppress artificial lighting'],
    ai_confidence: 0.93,
    ai_uncertainty: [],
    maintenance_required: false,
    reported_by: 'Suresh Menon (Admin Staff)',
    created_at: new Date(Date.now() - 14 * 3600 * 1000).toISOString(), // 14 hrs ago (open!)
    updated_at: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 20,
    eco_bounty_rewarded: false,
    ai_verified: true,
    assigned_department: 'Electrical Maintenance',
  },
  {
    id: 'GM-2026-009',
    title: 'Waste debris accumulation in drainage ditch',
    description: 'Leaves, beverage cans and plastic wrappers clogging the parking lot stormwater channel.',
    category: 'waste',
    location: 'Parking',
    severity: 'medium',
    status: 'in_progress',
    image_url: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Stormwater trench partially blocked by windblown plastic litter and seasonal organic detritus.',
    ai_observations: ['Drainage grate 60% covered by mixed debris', 'Stagnant water forming upstream'],
    ai_impact: 'Local flash flooding hazard during monsoon downpours; mosquito breeding in pooled run-off.',
    ai_recommendations: ['Rake and bag vegetative and plastic debris from grate', 'Ensure clear runoff flow'],
    ai_preventive_actions: ['Fit leaf-guards along open surface channels'],
    ai_confidence: 0.90,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Campus Safety Inspector',
    created_at: new Date(Date.now() - 20 * 3600 * 1000).toISOString(), // 20 hrs ago
    updated_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 30,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Facilities General',
  },
  {
    id: 'GM-2026-010',
    title: 'Canteen dishwashing hose running without nozzle',
    description: 'High-pressure wash hose left spraying onto floor without automatic shutoff spray trigger.',
    category: 'water',
    location: 'Canteen',
    severity: 'high',
    status: 'resolved',
    image_url: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=800&q=80',
    ai_summary: 'Commercial kitchen wash area utilizing un-valved open hose for floor rinse, wasting massive water volumes.',
    ai_observations: ['Open 1-inch hose discharging directly across wash tile floor', 'Lack of squeeze-trigger shutoff nozzle'],
    ai_impact: 'Severe potable water waste; grease buildup in sanitary sewer lines.',
    ai_recommendations: ['Shut supply valve C-4', 'Provide staff with heavy-duty squeeze shutoff spray gun'],
    ai_preventive_actions: ['Mandate water-saving spray nozzles on all kitchen hoses'],
    ai_confidence: 0.95,
    ai_uncertainty: [],
    maintenance_required: true,
    reported_by: 'Campus Sustainability Auditor',
    resolution_notes: 'Fitted auto-shutoff spray gun with brass quick-disconnect and trained kitchen staff.',
    created_at: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    eco_bounty_eligible: true,
    eco_bounty_points: 50,
    eco_bounty_rewarded: true,
    ai_verified: true,
    assigned_department: 'Plumbing & Water Services',
  }
];

// Pre-populate each issue with impact estimate and root cause analysis
export const INITIAL_DEMO_ISSUES: EnvironmentalIssue[] = RAW_ISSUES.map((issue) => {
  return {
    ...issue,
    impact_estimate: estimateResourceImpact(issue.category, issue.title, issue.description),
    root_cause_analysis: generateRootCauseAnalysis(
      issue.category,
      issue.title,
      issue.description,
      issue.location,
      RAW_ISSUES
    )
  };
});

export const INITIAL_ECO_STATS: EcoBountyStats = {
  myPoints: 1240,
  reportsSubmitted: 22,
  verifiedReports: 19,
  issuesResolved: 15,
  campusImpact: 38,
  weeklyEarned: 150,
};

export const DEMO_LEADERBOARD: EcoAuditor[] = [
  {
    id: 'user-001',
    name: 'Arun M.',
    department: 'Civil Engineering',
    points: 2450,
    weekly_points: 180,
    monthly_points: 620,
    verified_reports: 34,
    resolved_issues: 31,
    rank: 1,
    avatar: 'AM',
  },
  {
    id: 'user-002',
    name: 'Priya K.',
    department: 'Environmental Sciences',
    points: 2120,
    weekly_points: 150,
    monthly_points: 540,
    verified_reports: 29,
    resolved_issues: 26,
    rank: 2,
    avatar: 'PK',
  },
  {
    id: 'user-003',
    name: 'Elakkiyan (You)',
    department: 'Computer Science',
    points: 1240,
    weekly_points: 120,
    monthly_points: 380,
    verified_reports: 15,
    resolved_issues: 13,
    rank: 3,
    avatar: 'EL',
  },
  {
    id: 'user-004',
    name: 'Kavin R.',
    department: 'Mechanical Engineering',
    points: 1180,
    weekly_points: 90,
    monthly_points: 320,
    verified_reports: 14,
    resolved_issues: 11,
    rank: 4,
    avatar: 'KR',
  },
  {
    id: 'user-005',
    name: 'Sneha B.',
    department: 'Architecture & Design',
    points: 950,
    weekly_points: 70,
    monthly_points: 290,
    verified_reports: 12,
    resolved_issues: 10,
    rank: 5,
    avatar: 'SB',
  },
  {
    id: 'user-006',
    name: 'Rohan S.',
    department: 'Electrical Engineering',
    points: 820,
    weekly_points: 50,
    monthly_points: 240,
    verified_reports: 10,
    resolved_issues: 8,
    rank: 6,
    avatar: 'RS',
  }
];

export const DEMO_ACHIEVEMENTS = [
  {
    id: 'ach-1',
    title: 'First Report',
    icon: '🌱',
    description: 'Submitted first verified campus environmental issue',
    unlocked: true,
    dateUnlocked: '12 days ago',
  },
  {
    id: 'ach-2',
    title: 'Energy Saver',
    icon: '⚡',
    description: 'Identified 5+ active lighting or HVAC waste incidents',
    unlocked: true,
    dateUnlocked: '4 days ago',
  },
  {
    id: 'ach-3',
    title: 'Water Guardian',
    icon: '💧',
    description: 'Reported 3+ verified plumbing leaks or running taps',
    unlocked: true,
    dateUnlocked: 'Yesterday',
  },
  {
    id: 'ach-4',
    title: 'Waste Watcher',
    icon: '♻',
    description: 'Audited 5+ overflowing bins and plastic hotspots',
    unlocked: true,
    dateUnlocked: 'Just now',
  },
  {
    id: 'ach-5',
    title: 'Campus Eco Hero',
    icon: '🏆',
    description: 'Surpass 1,000 Eco Points and top your department',
    unlocked: true,
    dateUnlocked: '2 days ago',
  }
];

export const DEMO_REWARDS = [
  {
    id: 'rew-100',
    pointsCost: 100,
    title: 'Eco Auditor Badge',
    category: 'Digital Credential',
    description: 'Verified Student Sustainability Auditor badge on campus portal & resume portfolio.',
    icon: '🌱',
    isAvailable: true,
  },
  {
    id: 'rew-250',
    pointsCost: 250,
    title: 'Cafeteria Green Coupon',
    category: 'Campus Dining',
    description: '15% discount coupon on meals and zero-waste hot beverages at campus canteens.',
    icon: '☕',
    isAvailable: true,
  },
  {
    id: 'rew-500',
    pointsCost: 500,
    title: 'Eco Merchandise Pack',
    category: 'Sustainable Gear',
    description: 'Insulated stainless steel water bottle & organic hemp tote bag from Eco-Club.',
    icon: '🎒',
    isAvailable: true,
  },
  {
    id: 'rew-1000',
    pointsCost: 1000,
    title: 'Campus Eco Champion Honor',
    category: 'Dean Recognition',
    description: 'Official Certificate of Excellence signed by the Dean & Sustainability Committee.',
    icon: '🏆',
    isAvailable: true,
  }
];
