'use client';

import React, { useState } from 'react';
import { RecurringProblemPrediction } from '@/lib/types';
import CategoryBadge from '@/components/Common/CategoryBadge';
import { 
  AlertTriangle, 
  Sparkles, 
  Wrench, 
  Clock, 
  ShieldAlert, 
  Info, 
  TrendingUp,
  CheckCircle2,
  HelpCircle,
  Filter
} from 'lucide-react';

interface PredictedRecurringProblemsProps {
  predictions?: RecurringProblemPrediction[];
}

export default function PredictedRecurringProblems({ predictions = [] }: PredictedRecurringProblemsProps) {
  const [filterCategory, setFilterCategory] = useState<string>('all');

  const filtered = predictions.filter((p) => {
    if (filterCategory === 'all') return true;
    return p.category === filterCategory;
  });

  const categories = [
    { value: 'all', label: 'All Predictions' },
    { value: 'water', label: 'Water Leaks' },
    { value: 'energy', label: 'Energy Waste' },
    { value: 'waste', label: 'Waste Overflow' },
    { value: 'green_cover', label: 'Sprinklers / Grounds' },
  ];

  return (
    <div className="bg-white rounded-3xl p-6 sm:p-7 border border-[#E5EBE5] shadow-xs space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-gray-100 pb-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-black uppercase tracking-wider text-amber-900 bg-amber-100 px-2 py-0.5 rounded-md flex items-center gap-1 border border-amber-200">
              <Sparkles className="w-3 h-3 text-amber-600" />
              AI Predictive Intelligence
            </span>
            <span className="text-xs text-gray-500">• Pattern & Recurrence Modeling</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-black text-gray-900 tracking-tight flex items-center gap-2">
            <AlertTriangle className="w-6 h-6 text-amber-500" />
            <span>Predicted Recurring Problems</span>
          </h2>
          <p className="text-xs sm:text-sm text-gray-600 mt-1">
            Historical incident clustering identifies recurring operational vulnerabilities before severe failure.
          </p>
        </div>

        {/* Category Filter Pills */}
        <div className="flex flex-wrap items-center gap-1.5 self-start sm:self-auto">
          {categories.map((c) => (
            <button
              key={c.value}
              onClick={() => setFilterCategory(c.value)}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-colors ${
                filterCategory === c.value
                  ? 'bg-emerald-800 text-white shadow-xs'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              {c.label}
            </button>
          ))}
        </div>
      </div>

      {/* Mandatory AI Prediction Disclaimer Alert */}
      <div className="p-3.5 rounded-2xl bg-amber-50/70 border border-amber-200/80 flex items-start gap-3 text-xs text-amber-900">
        <Info className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
        <div className="space-y-0.5">
          <span className="font-bold block">Important Notice Regarding AI Predictions:</span>
          <p className="text-amber-800/90 leading-relaxed text-[11px]">
            Predictions shown below are generated by AI pattern modeling on historical reports. 
            They are intended for preventive prioritization and are <strong>not presented as guaranteed events</strong>. 
            Locations with limited report history will display insufficient data status.
          </p>
        </div>
      </div>

      {/* Predictions Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {filtered.map((item) => {
          if (item.insufficientData) {
            return (
              <div
                key={item.id}
                className="rounded-2xl p-5 border border-dashed border-gray-300 bg-gray-50/60 flex flex-col justify-between space-y-4"
              >
                <div>
                  <div className="flex items-center justify-between gap-2 mb-2">
                    <span className="font-bold text-sm text-gray-700 flex items-center gap-1.5">
                      <HelpCircle className="w-4 h-4 text-gray-400" />
                      {item.location}
                    </span>
                    <CategoryBadge category={item.category} />
                  </div>
                  <div className="p-4 rounded-xl bg-white border border-gray-200 text-center space-y-1.5">
                    <span className="text-xs font-bold text-gray-800 block">
                      ⚠ Not enough historical data for reliable prediction.
                    </span>
                    <p className="text-[11px] text-gray-500">
                      Minimum threshold of clustered reports not yet reached for statistical recurrence forecast.
                    </p>
                  </div>
                </div>

                <div className="flex items-center justify-between text-[11px] text-gray-500 pt-2 border-t border-gray-200/80 font-mono">
                  <span>Recorded Reports: {item.pastIncidentsCount}</span>
                  <span>Last: {item.lastOccurrenceFormatted}</span>
                </div>
              </div>
            );
          }

          const isHighRisk = item.recurrenceRisk === 'High';

          return (
            <div
              key={item.id}
              className={`rounded-2xl p-5 border transition-all duration-200 flex flex-col justify-between space-y-4 shadow-xs ${
                isHighRisk 
                  ? 'border-red-200 bg-gradient-to-br from-red-50/40 via-white to-orange-50/30' 
                  : 'border-amber-200 bg-gradient-to-br from-amber-50/30 via-white to-yellow-50/20'
              }`}
            >
              {/* Location & Risk Badge */}
              <div>
                <div className="flex items-start justify-between gap-3 mb-2">
                  <div className="flex items-center gap-2">
                    <div className={`p-1.5 rounded-lg ${isHighRisk ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'}`}>
                      <AlertTriangle className="w-4 h-4" />
                    </div>
                    <div>
                      <h3 className="font-black text-base text-gray-900 tracking-tight">
                        {item.location}
                      </h3>
                      <span className="text-[11px] font-semibold text-gray-500 block">
                        {item.categoryLabel}
                      </span>
                    </div>
                  </div>

                  <span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-wider border flex items-center gap-1 ${
                    isHighRisk
                      ? 'bg-red-100 text-red-800 border-red-200'
                      : 'bg-amber-100 text-amber-800 border-amber-200'
                  }`}>
                    <span className="w-1.5 h-1.5 rounded-full bg-current animate-pulse"></span>
                    {item.recurrenceRisk} Risk ({item.riskScore}%)
                  </span>
                </div>

                {/* Metrics Stats Row */}
                <div className="grid grid-cols-3 gap-2 my-3 p-3 rounded-xl bg-white/90 border border-gray-100 text-center">
                  <div>
                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                      Past Incidents
                    </span>
                    <span className="text-lg font-black text-gray-900 font-mono mt-0.5 block">
                      {item.pastIncidentsCount}
                    </span>
                  </div>

                  <div>
                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                      Last 30 Days
                    </span>
                    <span className={`text-lg font-black font-mono mt-0.5 block ${item.last30DaysCount >= 3 ? 'text-red-600' : 'text-amber-600'}`}>
                      {item.last30DaysCount}
                    </span>
                  </div>

                  <div>
                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">
                      Last Occurrence
                    </span>
                    <span className="text-xs font-bold text-gray-700 font-mono mt-1.5 block">
                      {item.lastOccurrenceFormatted}
                    </span>
                  </div>
                </div>

                {/* Pattern */}
                <div className="space-y-1 mb-3">
                  <span className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">
                    Observed Pattern:
                  </span>
                  <p className="text-xs text-gray-700 leading-relaxed font-medium">
                    {item.pattern}
                  </p>
                </div>

                {/* AI Prediction Callout */}
                <div className="p-3 rounded-xl bg-white border border-amber-200 shadow-2xs space-y-1 mb-3">
                  <span className="text-[10px] font-black uppercase tracking-wider text-amber-800 flex items-center gap-1">
                    <Sparkles className="w-3 h-3 text-amber-500" />
                    AI Prediction:
                  </span>
                  <p className="text-xs font-bold text-gray-900 leading-snug">
                    &ldquo;{item.aiPrediction}&rdquo;
                  </p>
                </div>

                {/* Recommended Action */}
                <div className="p-3 rounded-xl bg-emerald-50/80 border border-emerald-200/80 space-y-1">
                  <span className="text-[10px] font-black uppercase tracking-wider text-[#14532D] flex items-center gap-1">
                    <Wrench className="w-3 h-3 text-[#16A34A]" />
                    Recommended Action:
                  </span>
                  <p className="text-xs font-semibold text-gray-800 leading-snug">
                    {item.recommendedPreventiveAction}
                  </p>
                </div>
              </div>

              {/* Card Footer Tag */}
              <div className="pt-2 border-t border-gray-100 flex items-center justify-between text-[10px] text-gray-400">
                <span>AI Recurrence Model v2.4</span>
                <span className="font-semibold text-emerald-700">Preventive Priority</span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
